### ISSUE TITLE
Seed database does not work correctly with in-memory database

### ISSUE THREAD

**Issue by erikhofer** [code-freak/code-freak#23]
The in-memory databse should always be seeded, regardless of `dll-auto` setting

Seeding is broken:

```
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation;  table: "assignment_task" column: "files"
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.Table.generateAndCheckData(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	... 62 common frames omitted
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.types.BinaryType.castOrConvertToType(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.types.BinaryType.convertToTypeLimits(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	... 70 common frames omitted
```

**Comment by erikhofer** [comment]
We should include a test for this
